# Nome projeto
name: CoraDesafio

# Config de compilação
settings:
  MARKETING_VERSION: '1.0.0'
  CURRENT_PROJECT_VERSION: 1.0.0
  SWIFT_VERSION: 5.8
  CODE_SIGN_IDENTITY: 'iPhone Developer'
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"
  ARCHS: $(ARCHS_STANDARD)

options:
  bundleIdPrefix: br.com.Cora
  xcodeVersion: '15.4'
  deploymentTarget:
    iOS: '17.4'

include:
  - xcodegen/packages.yml
  - xcodegen/targets.yml
  - xcodegen/schemes.yml