# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'DesafioCora' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DesafioCora
  pod 'SnapKit', '~> 5.0.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'DesafioCoraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DesafioCoraUITests' do
    # Pods for testing
  end

end
