# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'desafio-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for desafio-ios
     pod 'SnapKit', '~> 5.0.0'

  target 'desafio-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'desafio-iosUITests' do
    # Pods for testing
  end

end
