target 'DesafioCoraBank' do
  use_frameworks!

  # Pods for DesafioCoraBank

  target 'DesafioCoraBankTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
  end

  target 'DesafioCoraBankUITests' do
    inherit! :search_paths
    pod 'KIF'
  end

end
